/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Parsedsms implements Serializable {

    private static final long serialVersionUID = -1250053572;

    private Long      id;
    private Long      rawsmsId;
    private String    addressFrom;
    private String    body;
    private Timestamp date;
    private String    identification;

    public Parsedsms() {}

    public Parsedsms(Parsedsms value) {
        this.id = value.id;
        this.rawsmsId = value.rawsmsId;
        this.addressFrom = value.addressFrom;
        this.body = value.body;
        this.date = value.date;
        this.identification = value.identification;
    }

    public Parsedsms(
        Long      id,
        Long      rawsmsId,
        String    addressFrom,
        String    body,
        Timestamp date,
        String    identification
    ) {
        this.id = id;
        this.rawsmsId = rawsmsId;
        this.addressFrom = addressFrom;
        this.body = body;
        this.date = date;
        this.identification = identification;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRawsmsId() {
        return this.rawsmsId;
    }

    public void setRawsmsId(Long rawsmsId) {
        this.rawsmsId = rawsmsId;
    }

    public String getAddressFrom() {
        return this.addressFrom;
    }

    public void setAddressFrom(String addressFrom) {
        this.addressFrom = addressFrom;
    }

    public String getBody() {
        return this.body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public Timestamp getDate() {
        return this.date;
    }

    public void setDate(Timestamp date) {
        this.date = date;
    }

    public String getIdentification() {
        return this.identification;
    }

    public void setIdentification(String identification) {
        this.identification = identification;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Parsedsms (");

        sb.append(id);
        sb.append(", ").append(rawsmsId);
        sb.append(", ").append(addressFrom);
        sb.append(", ").append(body);
        sb.append(", ").append(date);
        sb.append(", ").append(identification);

        sb.append(")");
        return sb.toString();
    }
}
