/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rawsms implements Serializable {

    private static final long serialVersionUID = -1297679663;

    private Long   id;
    private String smsBody;
    private Long   smsDate;
    private String deviceId;

    public Rawsms() {}

    public Rawsms(Rawsms value) {
        this.id = value.id;
        this.smsBody = value.smsBody;
        this.smsDate = value.smsDate;
        this.deviceId = value.deviceId;
    }

    public Rawsms(
        Long   id,
        String smsBody,
        Long   smsDate,
        String deviceId
    ) {
        this.id = id;
        this.smsBody = smsBody;
        this.smsDate = smsDate;
        this.deviceId = deviceId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSmsBody() {
        return this.smsBody;
    }

    public void setSmsBody(String smsBody) {
        this.smsBody = smsBody;
    }

    public Long getSmsDate() {
        return this.smsDate;
    }

    public void setSmsDate(Long smsDate) {
        this.smsDate = smsDate;
    }

    public String getDeviceId() {
        return this.deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Rawsms (");

        sb.append(id);
        sb.append(", ").append(smsBody);
        sb.append(", ").append(smsDate);
        sb.append(", ").append(deviceId);

        sb.append(")");
        return sb.toString();
    }
}
