/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.nazymko.moneygraph.storage.dao.autodao.Keys;
import org.nazymko.moneygraph.storage.dao.autodao.Moneygraph;
import org.nazymko.moneygraph.storage.dao.autodao.tables.records.ParsedsmsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Parsedsms extends TableImpl<ParsedsmsRecord> {

    private static final long serialVersionUID = -701678323;

    /**
     * The reference instance of <code>moneygraph.parsedsms</code>
     */
    public static final Parsedsms PARSEDSMS = new Parsedsms();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParsedsmsRecord> getRecordType() {
        return ParsedsmsRecord.class;
    }

    /**
     * The column <code>moneygraph.parsedsms.id</code>.
     */
    public final TableField<ParsedsmsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>moneygraph.parsedsms.rawsms_id</code>.
     */
    public final TableField<ParsedsmsRecord, Long> RAWSMS_ID = createField("rawsms_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>moneygraph.parsedsms.address_from</code>.
     */
    public final TableField<ParsedsmsRecord, String> ADDRESS_FROM = createField("address_from", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>moneygraph.parsedsms.body</code>.
     */
    public final TableField<ParsedsmsRecord, String> BODY = createField("body", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>moneygraph.parsedsms.date</code>.
     */
    public final TableField<ParsedsmsRecord, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>moneygraph.parsedsms.identification</code>.
     */
    public final TableField<ParsedsmsRecord, String> IDENTIFICATION = createField("identification", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "");

    /**
     * Create a <code>moneygraph.parsedsms</code> table reference
     */
    public Parsedsms() {
        this("parsedsms", null);
    }

    /**
     * Create an aliased <code>moneygraph.parsedsms</code> table reference
     */
    public Parsedsms(String alias) {
        this(alias, PARSEDSMS);
    }

    private Parsedsms(String alias, Table<ParsedsmsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Parsedsms(String alias, Table<ParsedsmsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Moneygraph.MONEYGRAPH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ParsedsmsRecord, Long> getIdentity() {
        return Keys.IDENTITY_PARSEDSMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ParsedsmsRecord> getPrimaryKey() {
        return Keys.KEY_PARSEDSMS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ParsedsmsRecord>> getKeys() {
        return Arrays.<UniqueKey<ParsedsmsRecord>>asList(Keys.KEY_PARSEDSMS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Parsedsms as(String alias) {
        return new Parsedsms(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Parsedsms rename(String name) {
        return new Parsedsms(name, null);
    }
}
