/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.nazymko.moneygraph.storage.dao.autodao.Keys;
import org.nazymko.moneygraph.storage.dao.autodao.Moneygraph;
import org.nazymko.moneygraph.storage.dao.autodao.tables.records.ParsedsmsDetailsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParsedsmsDetails extends TableImpl<ParsedsmsDetailsRecord> {

    private static final long serialVersionUID = -43260639;

    /**
     * The reference instance of <code>moneygraph.parsedsms_details</code>
     */
    public static final ParsedsmsDetails PARSEDSMS_DETAILS = new ParsedsmsDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParsedsmsDetailsRecord> getRecordType() {
        return ParsedsmsDetailsRecord.class;
    }

    /**
     * The column <code>moneygraph.parsedsms_details.id</code>.
     */
    public final TableField<ParsedsmsDetailsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>moneygraph.parsedsms_details.key</code>.
     */
    public final TableField<ParsedsmsDetailsRecord, String> KEY = createField("key", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>moneygraph.parsedsms_details.value</code>.
     */
    public final TableField<ParsedsmsDetailsRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>moneygraph.parsedsms_details.value_type</code>.
     */
    public final TableField<ParsedsmsDetailsRecord, String> VALUE_TYPE = createField("value_type", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>moneygraph.parsedsms_details.parsedsms_id</code>.
     */
    public final TableField<ParsedsmsDetailsRecord, Long> PARSEDSMS_ID = createField("parsedsms_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>moneygraph.parsedsms_details</code> table reference
     */
    public ParsedsmsDetails() {
        this("parsedsms_details", null);
    }

    /**
     * Create an aliased <code>moneygraph.parsedsms_details</code> table reference
     */
    public ParsedsmsDetails(String alias) {
        this(alias, PARSEDSMS_DETAILS);
    }

    private ParsedsmsDetails(String alias, Table<ParsedsmsDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ParsedsmsDetails(String alias, Table<ParsedsmsDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Moneygraph.MONEYGRAPH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ParsedsmsDetailsRecord, Long> getIdentity() {
        return Keys.IDENTITY_PARSEDSMS_DETAILS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ParsedsmsDetailsRecord> getPrimaryKey() {
        return Keys.KEY_PARSEDSMS_DETAILS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ParsedsmsDetailsRecord>> getKeys() {
        return Arrays.<UniqueKey<ParsedsmsDetailsRecord>>asList(Keys.KEY_PARSEDSMS_DETAILS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsDetails as(String alias) {
        return new ParsedsmsDetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ParsedsmsDetails rename(String name) {
        return new ParsedsmsDetails(name, null);
    }
}
