/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.nazymko.moneygraph.storage.dao.autodao.Keys;
import org.nazymko.moneygraph.storage.dao.autodao.Moneygraph;
import org.nazymko.moneygraph.storage.dao.autodao.tables.records.RawsmsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rawsms extends TableImpl<RawsmsRecord> {

    private static final long serialVersionUID = 1686265063;

    /**
     * The reference instance of <code>moneygraph.rawsms</code>
     */
    public static final Rawsms RAWSMS = new Rawsms();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RawsmsRecord> getRecordType() {
        return RawsmsRecord.class;
    }

    /**
     * The column <code>moneygraph.rawsms.id</code>.
     */
    public final TableField<RawsmsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>moneygraph.rawsms.sms_body</code>.
     */
    public final TableField<RawsmsRecord, String> SMS_BODY = createField("sms_body", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>moneygraph.rawsms.sms_date</code>.
     */
    public final TableField<RawsmsRecord, Long> SMS_DATE = createField("sms_date", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>moneygraph.rawsms.device_id</code>.
     */
    public final TableField<RawsmsRecord, String> DEVICE_ID = createField("device_id", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "");

    /**
     * Create a <code>moneygraph.rawsms</code> table reference
     */
    public Rawsms() {
        this("rawsms", null);
    }

    /**
     * Create an aliased <code>moneygraph.rawsms</code> table reference
     */
    public Rawsms(String alias) {
        this(alias, RAWSMS);
    }

    private Rawsms(String alias, Table<RawsmsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Rawsms(String alias, Table<RawsmsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Moneygraph.MONEYGRAPH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RawsmsRecord, Long> getIdentity() {
        return Keys.IDENTITY_RAWSMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RawsmsRecord> getPrimaryKey() {
        return Keys.KEY_RAWSMS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RawsmsRecord>> getKeys() {
        return Arrays.<UniqueKey<RawsmsRecord>>asList(Keys.KEY_RAWSMS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Rawsms as(String alias) {
        return new Rawsms(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Rawsms rename(String name) {
        return new Rawsms(name, null);
    }
}
