/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.moneygraph.storage.dao.autodao.tables.ParsedsmsDetails;
import org.nazymko.moneygraph.storage.dao.autodao.tables.records.ParsedsmsDetailsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqParsedsmsDetailsDao extends DAOImpl<ParsedsmsDetailsRecord, org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.ParsedsmsDetails, Long> {

    /**
     * Create a new JooqParsedsmsDetailsDao without any configuration
     */
    public JooqParsedsmsDetailsDao() {
        super(ParsedsmsDetails.PARSEDSMS_DETAILS, org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.ParsedsmsDetails.class);
    }

    /**
     * Create a new JooqParsedsmsDetailsDao with an attached configuration
     */
    public JooqParsedsmsDetailsDao(Configuration configuration) {
        super(ParsedsmsDetails.PARSEDSMS_DETAILS, org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.ParsedsmsDetails.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.ParsedsmsDetails object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.ParsedsmsDetails> fetchById(Long... values) {
        return fetch(ParsedsmsDetails.PARSEDSMS_DETAILS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.ParsedsmsDetails fetchOneById(Long value) {
        return fetchOne(ParsedsmsDetails.PARSEDSMS_DETAILS.ID, value);
    }

    /**
     * Fetch records that have <code>key IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.ParsedsmsDetails> fetchByKey(String... values) {
        return fetch(ParsedsmsDetails.PARSEDSMS_DETAILS.KEY, values);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.ParsedsmsDetails> fetchByValue(String... values) {
        return fetch(ParsedsmsDetails.PARSEDSMS_DETAILS.VALUE, values);
    }

    /**
     * Fetch records that have <code>value_type IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.ParsedsmsDetails> fetchByValueType(String... values) {
        return fetch(ParsedsmsDetails.PARSEDSMS_DETAILS.VALUE_TYPE, values);
    }

    /**
     * Fetch records that have <code>parsedsms_id IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.ParsedsmsDetails> fetchByParsedsmsId(Long... values) {
        return fetch(ParsedsmsDetails.PARSEDSMS_DETAILS.PARSEDSMS_ID, values);
    }
}
