/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.moneygraph.storage.dao.autodao.tables.Parsedsms;
import org.nazymko.moneygraph.storage.dao.autodao.tables.records.ParsedsmsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqParsedsmsDao extends DAOImpl<ParsedsmsRecord, org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Parsedsms, Long> {

    /**
     * Create a new JooqParsedsmsDao without any configuration
     */
    public JooqParsedsmsDao() {
        super(Parsedsms.PARSEDSMS, org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Parsedsms.class);
    }

    /**
     * Create a new JooqParsedsmsDao with an attached configuration
     */
    public JooqParsedsmsDao(Configuration configuration) {
        super(Parsedsms.PARSEDSMS, org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Parsedsms.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Parsedsms object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Parsedsms> fetchById(Long... values) {
        return fetch(Parsedsms.PARSEDSMS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Parsedsms fetchOneById(Long value) {
        return fetchOne(Parsedsms.PARSEDSMS.ID, value);
    }

    /**
     * Fetch records that have <code>rawsms_id IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Parsedsms> fetchByRawsmsId(Long... values) {
        return fetch(Parsedsms.PARSEDSMS.RAWSMS_ID, values);
    }

    /**
     * Fetch records that have <code>address_from IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Parsedsms> fetchByAddressFrom(String... values) {
        return fetch(Parsedsms.PARSEDSMS.ADDRESS_FROM, values);
    }

    /**
     * Fetch records that have <code>body IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Parsedsms> fetchByBody(String... values) {
        return fetch(Parsedsms.PARSEDSMS.BODY, values);
    }

    /**
     * Fetch records that have <code>date IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Parsedsms> fetchByDate(Timestamp... values) {
        return fetch(Parsedsms.PARSEDSMS.DATE, values);
    }

    /**
     * Fetch records that have <code>identification IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Parsedsms> fetchByIdentification(String... values) {
        return fetch(Parsedsms.PARSEDSMS.IDENTIFICATION, values);
    }
}
