/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.moneygraph.storage.dao.autodao.tables.Rawsms;
import org.nazymko.moneygraph.storage.dao.autodao.tables.records.RawsmsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqRawsmsDao extends DAOImpl<RawsmsRecord, org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Rawsms, Long> {

    /**
     * Create a new JooqRawsmsDao without any configuration
     */
    public JooqRawsmsDao() {
        super(Rawsms.RAWSMS, org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Rawsms.class);
    }

    /**
     * Create a new JooqRawsmsDao with an attached configuration
     */
    public JooqRawsmsDao(Configuration configuration) {
        super(Rawsms.RAWSMS, org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Rawsms.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Rawsms object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Rawsms> fetchById(Long... values) {
        return fetch(Rawsms.RAWSMS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Rawsms fetchOneById(Long value) {
        return fetchOne(Rawsms.RAWSMS.ID, value);
    }

    /**
     * Fetch records that have <code>sms_body IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Rawsms> fetchBySmsBody(String... values) {
        return fetch(Rawsms.RAWSMS.SMS_BODY, values);
    }

    /**
     * Fetch records that have <code>sms_date IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Rawsms> fetchBySmsDate(Long... values) {
        return fetch(Rawsms.RAWSMS.SMS_DATE, values);
    }

    /**
     * Fetch records that have <code>device_id IN (values)</code>
     */
    public List<org.nazymko.moneygraph.storage.dao.autodao.tables.pojos.Rawsms> fetchByDeviceId(String... values) {
        return fetch(Rawsms.RAWSMS.DEVICE_ID, values);
    }
}
