/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.moneygraph.storage.dao.autodao.tables.ParsedsmsDetails;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParsedsmsDetailsRecord extends UpdatableRecordImpl<ParsedsmsDetailsRecord> implements Record5<Long, String, String, String, Long> {

    private static final long serialVersionUID = 1970415165;

    /**
     * Setter for <code>moneygraph.parsedsms_details.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>moneygraph.parsedsms_details.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>moneygraph.parsedsms_details.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>moneygraph.parsedsms_details.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>moneygraph.parsedsms_details.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>moneygraph.parsedsms_details.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>moneygraph.parsedsms_details.value_type</code>.
     */
    public void setValueType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>moneygraph.parsedsms_details.value_type</code>.
     */
    public String getValueType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>moneygraph.parsedsms_details.parsedsms_id</code>.
     */
    public void setParsedsmsId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>moneygraph.parsedsms_details.parsedsms_id</code>.
     */
    public Long getParsedsmsId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ParsedsmsDetails.PARSEDSMS_DETAILS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ParsedsmsDetails.PARSEDSMS_DETAILS.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ParsedsmsDetails.PARSEDSMS_DETAILS.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ParsedsmsDetails.PARSEDSMS_DETAILS.VALUE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return ParsedsmsDetails.PARSEDSMS_DETAILS.PARSEDSMS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getValueType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getParsedsmsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsDetailsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsDetailsRecord value2(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsDetailsRecord value3(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsDetailsRecord value4(String value) {
        setValueType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsDetailsRecord value5(Long value) {
        setParsedsmsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsDetailsRecord values(Long value1, String value2, String value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParsedsmsDetailsRecord
     */
    public ParsedsmsDetailsRecord() {
        super(ParsedsmsDetails.PARSEDSMS_DETAILS);
    }

    /**
     * Create a detached, initialised ParsedsmsDetailsRecord
     */
    public ParsedsmsDetailsRecord(Long id, String key, String value, String valueType, Long parsedsmsId) {
        super(ParsedsmsDetails.PARSEDSMS_DETAILS);

        set(0, id);
        set(1, key);
        set(2, value);
        set(3, valueType);
        set(4, parsedsmsId);
    }
}
