/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.moneygraph.storage.dao.autodao.tables.Parsedsms;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParsedsmsRecord extends UpdatableRecordImpl<ParsedsmsRecord> implements Record6<Long, Long, String, String, Timestamp, String> {

    private static final long serialVersionUID = 309689211;

    /**
     * Setter for <code>moneygraph.parsedsms.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>moneygraph.parsedsms.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>moneygraph.parsedsms.rawsms_id</code>.
     */
    public void setRawsmsId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>moneygraph.parsedsms.rawsms_id</code>.
     */
    public Long getRawsmsId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>moneygraph.parsedsms.address_from</code>.
     */
    public void setAddressFrom(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>moneygraph.parsedsms.address_from</code>.
     */
    public String getAddressFrom() {
        return (String) get(2);
    }

    /**
     * Setter for <code>moneygraph.parsedsms.body</code>.
     */
    public void setBody(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>moneygraph.parsedsms.body</code>.
     */
    public String getBody() {
        return (String) get(3);
    }

    /**
     * Setter for <code>moneygraph.parsedsms.date</code>.
     */
    public void setDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>moneygraph.parsedsms.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>moneygraph.parsedsms.identification</code>.
     */
    public void setIdentification(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>moneygraph.parsedsms.identification</code>.
     */
    public String getIdentification() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, String, String, Timestamp, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, String, String, Timestamp, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Parsedsms.PARSEDSMS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Parsedsms.PARSEDSMS.RAWSMS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Parsedsms.PARSEDSMS.ADDRESS_FROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Parsedsms.PARSEDSMS.BODY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Parsedsms.PARSEDSMS.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Parsedsms.PARSEDSMS.IDENTIFICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getRawsmsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAddressFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getIdentification();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsRecord value2(Long value) {
        setRawsmsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsRecord value3(String value) {
        setAddressFrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsRecord value4(String value) {
        setBody(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsRecord value5(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsRecord value6(String value) {
        setIdentification(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParsedsmsRecord values(Long value1, Long value2, String value3, String value4, Timestamp value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParsedsmsRecord
     */
    public ParsedsmsRecord() {
        super(Parsedsms.PARSEDSMS);
    }

    /**
     * Create a detached, initialised ParsedsmsRecord
     */
    public ParsedsmsRecord(Long id, Long rawsmsId, String addressFrom, String body, Timestamp date, String identification) {
        super(Parsedsms.PARSEDSMS);

        set(0, id);
        set(1, rawsmsId);
        set(2, addressFrom);
        set(3, body);
        set(4, date);
        set(5, identification);
    }
}
