/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.moneygraph.storage.dao.autodao.tables.Rawsms;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RawsmsRecord extends UpdatableRecordImpl<RawsmsRecord> implements Record4<Long, String, Long, String> {

    private static final long serialVersionUID = -1212979773;

    /**
     * Setter for <code>moneygraph.rawsms.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>moneygraph.rawsms.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>moneygraph.rawsms.sms_body</code>.
     */
    public void setSmsBody(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>moneygraph.rawsms.sms_body</code>.
     */
    public String getSmsBody() {
        return (String) get(1);
    }

    /**
     * Setter for <code>moneygraph.rawsms.sms_date</code>.
     */
    public void setSmsDate(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>moneygraph.rawsms.sms_date</code>.
     */
    public Long getSmsDate() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>moneygraph.rawsms.device_id</code>.
     */
    public void setDeviceId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>moneygraph.rawsms.device_id</code>.
     */
    public String getDeviceId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Long, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Long, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Rawsms.RAWSMS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Rawsms.RAWSMS.SMS_BODY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Rawsms.RAWSMS.SMS_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Rawsms.RAWSMS.DEVICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSmsBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getSmsDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDeviceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RawsmsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RawsmsRecord value2(String value) {
        setSmsBody(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RawsmsRecord value3(Long value) {
        setSmsDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RawsmsRecord value4(String value) {
        setDeviceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RawsmsRecord values(Long value1, String value2, Long value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RawsmsRecord
     */
    public RawsmsRecord() {
        super(Rawsms.RAWSMS);
    }

    /**
     * Create a detached, initialised RawsmsRecord
     */
    public RawsmsRecord(Long id, String smsBody, Long smsDate, String deviceId) {
        super(Rawsms.RAWSMS);

        set(0, id);
        set(1, smsBody);
        set(2, smsDate);
        set(3, deviceId);
    }
}
