/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.nazymko.moneygraph.storage.dao.autodao.tables.Rawsms;
import org.nazymko.moneygraph.storage.dao.autodao.tables.records.RawsmsRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>moneygraph</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RawsmsRecord, Long> IDENTITY_RAWSMS = Identities0.IDENTITY_RAWSMS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RawsmsRecord> KEY_RAWSMS_PRIMARY = UniqueKeys0.KEY_RAWSMS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<RawsmsRecord, Long> IDENTITY_RAWSMS = createIdentity(Rawsms.RAWSMS, Rawsms.RAWSMS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<RawsmsRecord> KEY_RAWSMS_PRIMARY = createUniqueKey(Rawsms.RAWSMS, "KEY_rawsms_PRIMARY", Rawsms.RAWSMS.ID);
    }
}
