/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.nazymko.moneygraph.storage.dao.autodao.tables.Parsedsms;
import org.nazymko.moneygraph.storage.dao.autodao.tables.ParsedsmsDetails;
import org.nazymko.moneygraph.storage.dao.autodao.tables.Rawsms;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Moneygraph extends SchemaImpl {

    private static final long serialVersionUID = 1453633090;

    /**
     * The reference instance of <code>moneygraph</code>
     */
    public static final Moneygraph MONEYGRAPH = new Moneygraph();

    /**
     * The table <code>moneygraph.parsedsms</code>.
     */
    public final Parsedsms PARSEDSMS = org.nazymko.moneygraph.storage.dao.autodao.tables.Parsedsms.PARSEDSMS;

    /**
     * The table <code>moneygraph.parsedsms_details</code>.
     */
    public final ParsedsmsDetails PARSEDSMS_DETAILS = org.nazymko.moneygraph.storage.dao.autodao.tables.ParsedsmsDetails.PARSEDSMS_DETAILS;

    /**
     * The table <code>moneygraph.rawsms</code>.
     */
    public final Rawsms RAWSMS = org.nazymko.moneygraph.storage.dao.autodao.tables.Rawsms.RAWSMS;

    /**
     * No further instances allowed
     */
    private Moneygraph() {
        super("moneygraph", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Parsedsms.PARSEDSMS,
            ParsedsmsDetails.PARSEDSMS_DETAILS,
            Rawsms.RAWSMS);
    }
}
