/*
 * This file is generated by jOOQ.
*/
package org.nazymko.moneygraph.storage.dao.autodao;


import javax.annotation.Generated;

import org.nazymko.moneygraph.storage.dao.autodao.tables.Rawsms;


/**
 * Convenience access to all tables in moneygraph
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>moneygraph.rawsms</code>.
     */
    public static final Rawsms RAWSMS = org.nazymko.moneygraph.storage.dao.autodao.tables.Rawsms.RAWSMS;
}
